all: swap reverse_array transpose_matrix reverse_list

swap: swap.c
	$(CC) -o swap swap.c

reverse_array: reverse_array.c
	$(CC) -o reverse_array reverse_array.c

transpose_matrix: transpose_matrix.c
	$(CC) -o transpose_matrix transpose_matrix.c

reverse_list: reverse_list.c
	$(CC) -o reverse_list reverse_list.c

clean:
	rm -f swap reverse_array transpose_matrix reverse_list *.o out.txt
